version: "2.0"

services:
  csysmariadb:
     container_name: CancersysMariaDB
     build:
       context: ./csys-mariadb
       dockerfile: Dockerfile
     environment:
       MYSQL_USER: csysUser
       MYSQL_PASSWORD: csysPassword
       MYSQL_DATABASE: cancersys
       MYSQL_ROOT_PASSWORD: csysRootPW
     ports:
       - "3030"
     networks:
        - csysnetwork

  cancersys:
     container_name: Cancersys
     build:
       context: ./openImage
       dockerfile: Dockerfile
     networks:
       - csysnetwork
     links:
       - csysmariadb
     ports:
       - "8075:8080"


networks:
    csysnetwork:
        driver: bridge